import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  monthHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    marginLeft: 12,
  },
  monthText: { fontSize: 18, fontWeight: "bold", marginLeft: 4 },
  calendarContainer: {
    backgroundColor: "#fff",
    height: 350,
    overflow: "hidden",
  },
  daysRow: {
    flexDirection: "row",
    width: "88%",
    left: "12%",
    marginTop: 8,
  },
  dayCol: { alignItems: "center", flex: 1 },
  dayText: { fontSize: 13, color: "#888" },
  dateText: { fontSize: 13, color: "#888", marginTop: 2 },
  todayText: {
    fontSize: 13,
    color: "#000",
    fontWeight: "bold",
    marginTop: 2,
  },
  scrollArea: { flex: 1 },
  gridContainer: { flexDirection: "row", minHeight: 40 * 23, marginTop: 8 },
  timeCol: { width: 40, alignItems: "flex-end", paddingRight: 4 },
  timeText: { height: 40, fontSize: 12, color: "#888" },
  gridContent: { flex: 1, marginLeft: 8 },
  gridRow: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "#ddd",
  },
  gridCol: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "#ddd",
  },
  eventBlock: {
    position: "absolute",
    width: 48,
    height: 40,
    backgroundColor: "#4CAF50",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  eventText: { color: "#fff", fontSize: 15 },
  fab: {
    position: "absolute",
    right: 24,
    bottom: 48,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#4CAF50",
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
  fabEdit: {
    backgroundColor: "#000",
  },
  // 모달 스타일 추가
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  modalContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "20%",
    marginHorizontal: 0,
    backgroundColor: "#F5F5F5",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 32,
    elevation: 8,
  },
  calendarPickerContainer: {
    backgroundColor: "#F5F5F5",
    borderRadius: 16,
    padding: 12,
    marginVertical: 8,
    marginHorizontal: 0,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 40,
    marginHorizontal: 20,
  },
  modalCancel: {
    fontSize: 16,
    color: "#888",
  },
  modalSave: {
    fontSize: 16,
    color: "#4CAF50",
    fontWeight: "bold",
  },
  modalTitleInput: {
    fontSize: 24,
    color: "#222",
    marginBottom: 20,
    marginHorizontal: 40,
  },
  modalRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 19,
    marginHorizontal: 40,
  },
  modalDate: {
    fontSize: 15,
    color: "#888",
    flex: 1,
  },
  modalTime: {
    fontSize: 15,
    color: "#888",
    textAlign: "right",
    flex: 1,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#ddd",
    marginVertical: 4,
  },
  modalRepeat: {
    fontSize: 16,
    color: "#888",
  },
  modalDisabled: {
    fontSize: 15,
    color: "#bbb",
  },
  modalContainerSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 250,
    backgroundColor: "#F5F5F5",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
  },
});

export default styles;
